apiVersion: v1
kind: Service
metadata:
  labels:
    service-label-key: service-label-value
  name: agnular-webserver-loadbalancer
spec:
  type: LoadBalancer
  ports:
  - name: service-port-angular-webserver
    port: 80
    protocol: TCP
  selector:
    deployment-label-key: deployment-label-value
